version: "3"

services:
  camaps-diasend-bridge:
    image: node:18-alpine
    restart: always
    container_name: camaps-diasend-bridge
    volumes:
      - $CAMAPS:/app:cached
    working_dir: /app
    command: sh -c "yarn && yarn start"
    env_file: $CAMAPS/diasend.env
    depends_on: 
      - nightscout